# script de build automatizado da aplicacao
name: Sigachat construcao

on:
 push:
  branches:
  - "main"
jobs:
 construcao-app:
  runs-on: ubuntu-latest
  steps:
  - name: baixar codigo fonte
    uses: actions/checkout@v4